### ISSUE TITLE
Archetype parameter types

### ISSUE THREAD

**Issue by adam-tg** [UBC-NSS/pgo#101]
This is a braindump of what I've been thinking about (in the form of 3 design questions) before I move on to the paper and eval. Typechecking MPCal seems to be basically the same as typechecking Vanilla PlusCal, with the exception of archetype parameters. For parameters, I think it is best to type inference on values read from/written to parameters, and to validate that those types fit with the mapping macro for that parameter (which will solve one of the problems from #98). 

My first question is whether we want to give types to archetype parameters themselves (beyond ref and readonly). I don't think this will affect anything visible (because parameters are only interacted with via reads/writes), and I think it will be easier to implement without types because you would have to rely on the mapping macros (when present) for type information. It is also of note that parameter types are abstracted to read/write interfaces when they are compiled to Go, so I do not think we are missing anything by not inferring parameter types.

My second question relates to how much type information we want to carry through compilation. Parameters will have an interface type similar to this:
`type Param interface {
	Read()
	Write()
}`
This question is really abut the types of the Read/Write functions in the interface. For example, if based on type inference in MPCal, we see that strings are written to and read from a parameter, we could make the type interface to look like:
`type Param interface {
	Read() string
	Write(string)
}`
Our other option, to provide more flexibility to the user, is to instead have the following always be the type interface:
`type Param interface {
	Read() interface{}
	Write(interface{})
}`
My concern with the second option is that it may cause issues with Go typechecking. Thoughts?

Finally, my third question is about ref parameters and readonly parameters. When we compile them to Go, do we want to simply have two interfaces like this:
 `type RefParam interface {
	Read() ...
	Write(...)
}
type ROParam interface {
	Read() ...
}`
Or do we want to make ref parameters a bit more explicit to the programmer (so they are less likely to mess up and forget an indirection) by making them pointers in the compiled archetype? With this option (and the same above types), a compiled archetype would look like this:
`func Archetype(refparam *RefParam) {
	...
}
`

**Comment by fhackett** [comment]
Some comments from our previous meeting, themed around lexically enforcing channel vs. variable semantics.

The background for the idea is that sometimes a variable isn't really a variable - it's trying to represent a communication channel of some kind. Now it is usually possible to emulate some approximation of a variable while emulating communication semantics (i.e making sure each process sees some sequentially consistent series of events via careful algorithm-ing), but a duplex TCP connection for example does not work like that. If instead of being forced to make something look like a variable programmers could specify that something is a channel instead (and lose the expectation that you can read back what you sent). Maybe then algorithm designers may have an easier time.

To summarise the changes proposed, we would still have archetypes and mapping macros as usual. The difference would be a different archetype parameter type called `chan`, which can be read and written. This would compile identically to a normal archetype parameter, but would indicate that it should be thought of as send/receive, not something variable-like. One could then implement these send/receive semantics via a mapping macro like the ones already discussed in other issues/PRs.

For example, a parameter `chan x` could be read using `read x` in an expression and written using `write x <- ...` as a PlusCal statement. While these would just be syntactic sugar for `x` (just a variable reference) and `x := ...` respectively, we could enforce things like "read only once per critical section" if we wanted to (if it helps people avoid bad mistakes).

**Comment by rmascarenhas** [comment]
Outdated discussion.
