### ISSUE TITLE
Support TLA+ records

### ISSUE THREAD

**Issue by rmascarenhas** [UBC-NSS/pgo#108]
TLA+ records are a very attractive way to model network messages. Currently we use tuples, which are ok but makes the specification harder to understand.

This may be harder to support than it sounds due to #106.

**Comment by fhackett** [comment]
@rmascarenhas don't we already have some (limited) support for records?

I specifically remember contributing some of the codegen for those.

**Comment by rmascarenhas** [comment]
I believe there is some support, yes (i.e., I think we can parse it, and maybe there's some code gen), but it currently fails to understand records. This remains an open issue until we can successfully use them in specs.

**Comment by fhackett** [comment]
Ah I see. Terminology nit: those aren't records, they're just a specific function definition syntax.

Interesting that scoping fails under those conditions. I double checked and the behaviour you described is simply wrong. I probably have something to answer for there - let me know when this issue is being worked on and I can help fix the scoping code.

**Comment by rmascarenhas** [comment]
Yes, scoping is definitely wrong there, hence the issue! :-)

As for the nit -- well, yes, technically even tuples are functions. TLA+ seems to refer to expressions like the one I wrote before as records (or, at least, it does here [1]), but I might have confused the terms.

The fact is that it would great to use those with PGo!

[1] https://lamport.azurewebsites.net/tla/summary.pdf

**Comment by mrordinaire** [comment]
Fixed on master. See d7c595f for example use.
