### ISSUE TITLE
Wrong macro expansion in PlusCal compilation

### ISSUE THREAD

**Issue by shayanh** [UBC-NSS/pgo#195]
Seems that there is a bug in macro expansion when compiling to PlusCal. The attached spec has a macro named `Merge`. `Merge` is only used in `UpdateCRDT` process. Compiled PlusCal code of `UpdateCRDT` definitely misses some parts of `Merge`.

Spec: https://gist.github.com/shayanh/c67308f3721322f707cdbc48d942afba

**Comment by fhackett** [comment]
Are you sure?

It would help if you could point out exactly which parts, because I've read through it multiple times, and all the parts are there, that I can see at least.

Maybe a difficulty is that in this case PGo translates `crdt[i1].addMap := ...` to `with(crdt1 = [crdt0 EXCEPT ![i1]["addMap"] = ... ]) {`. It looks like it skipped the body of the `with` statements in the original macro, but it just rewrote them into more `with` statements as a normalisation step.

**Comment by shayanh** [comment]
I missed that `crdt` is updated through `with` statements. However, assignment to `crdt` in line 141 should use `crdt2` (the latest), not `crdt1`.

**Comment by fhackett** [comment]
I see. Yes, that's a bug all right.
