### ISSUE TITLE
connection keep alive in state server when variable is being used in another process's critical section 

### ISSUE THREAD

**Issue by mrordinaire** [UBC-NSS/pgo#56]

**Comment by rmascarenhas** [comment]
Forgot exactly what this issue was referring to. We currently use standard Go RPC, which runs on top of TPC, and keep alive settings can be configured on Linux separately. We could maybe add our own OS-independent solution, but I see that as low priority unless we have a concrete scenario where that would be helpful or needed.

Therefore, closing this for now.
