### ISSUE TITLE
 Treat tuples formed by cartesian product properly 

### ISSUE THREAD

**Issue by minhnhdo** [UBC-NSS/pgo#7]
The Go set library uses a pair type to represent cartesian products. This is a problem when representing tuples of more than two elements, as the implementation of the cartesian product is not associative. We need to define our own Go tuple type and corresponding library functions. This is complicated by the fact that the TLA cartesian product operator changes meaning depending on how it is parenthesized:

- `<< 1, 2, 3 >> is in Nat \X Nat \X Nat`
- `<< 1, << 2, 3 >> >> is in Nat \X (Nat \X Nat)`
- `<< << 1, 2 >>, 3 >> is in (Nat \X Nat) \X Nat`

and none of the above are equivalent.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/31/treat-tuples-formed-by-cartesian-product

**Comment by mrordinaire** [comment]
What if we reused slices to represent tuples? Tuples aren't far off from slices

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/31/treat-tuples-formed-by-cartesian-product#comment-37468460

**Comment by mrordinaire** [comment]
The problem with slices is that we can't use them as map keys, which we need if we want to use arrays indexed by tuples or make sets of tuples. I'm considering making a wrapper to the map object that will let us define a hash function for slices so that we can use them with maps.

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/31/treat-tuples-formed-by-cartesian-product#comment-37468579

**Comment by mrordinaire** [comment]
Wrapper will also require you to change the Set library to use the wrapper. Let's discuss pros and cons at the meeting later.

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/31/treat-tuples-formed-by-cartesian-product#comment-37468616

**Comment by mrordinaire** [comment]
A cartesian product method that produces tuples in the same way as TLA+ was added in ac1a3ef. The TLAExprParser needs to parse the cartesian product operator as a variadic in order to use this method properly.

Original comment: https://bitbucket.org/whiteoutblackout/pgo/issues/31/treat-tuples-formed-by-cartesian-product#comment-37932846

**Comment by fhackett** [comment]
This was addressed completely by #154. It works now!
